# Makefile for the Magnetohydrodynamics (HD) Module 

VPATH        +=  mmd_convection_set/HD
INCLUDE_DIRS +=  -Immd_convection_set/HD

HEADERS += hd_convection.h

OBJ   += hd_next_time_step.o hd_integrate.o hd_rk_step.o \
         hd_update_stage.o hd_mappers3D.o hd_set_indexes.o \
         hd_set_output.o hd_var_names.o       
