# Makefile for the Magnetohydrodynamics (MHD) Module 

VPATH        +=  mmd_convection_set/MHD
INCLUDE_DIRS +=  -Immd_convection_set/MHD

HEADERS += mhd_convection.h

OBJ   += mhd_next_time_step.o mhd_integrate.o mhd_rk_step.o\
         mhd_update_stage.o mhd_mappers3D.o mhd_startup.o mhd_set_indexes.o \
         mhd_boundary.o mhd_set_output.o mhd_var_names.o
         #            
